apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test2
  name: test2
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test2
  template:
    metadata:
      labels:
        app: test2
    spec:
      containers:
      - image: httpd:alpine3.18
        name: httpd
        command: ["/bin/bash","-c"]
        args: ["sleep 5; exit 1"] #sleep 5 s, then exit with error (to simulate a failue)
  strategy:      
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
      